// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

#ifndef PROTOBUF_model_2eproto__INCLUDED
#define PROTOBUF_model_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace yreflection {
namespace model {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_model_2eproto();
void protobuf_AssignDesc_model_2eproto();
void protobuf_ShutdownFile_model_2eproto();

class Email;
class Message;
class Messages;
class Recipient;

// ===================================================================

class Email : public ::google::protobuf::Message {
 public:
  Email();
  virtual ~Email();

  Email(const Email& from);

  inline Email& operator=(const Email& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Email& default_instance();

  void Swap(Email* other);

  // implements Message ----------------------------------------------

  inline Email* New() const { return New(NULL); }

  Email* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Email& from);
  void MergeFrom(const Email& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Email* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string address = 2;
  bool has_address() const;
  void clear_address();
  static const int kAddressFieldNumber = 2;
  const ::std::string& address() const;
  void set_address(const ::std::string& value);
  void set_address(const char* value);
  void set_address(const char* value, size_t size);
  ::std::string* mutable_address();
  ::std::string* release_address();
  void set_allocated_address(::std::string* address);

  // @@protoc_insertion_point(class_scope:yreflection.model.Email)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_address();
  inline void clear_has_address();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr address_;
  friend void  protobuf_AddDesc_model_2eproto();
  friend void protobuf_AssignDesc_model_2eproto();
  friend void protobuf_ShutdownFile_model_2eproto();

  void InitAsDefaultInstance();
  static Email* default_instance_;
};
// -------------------------------------------------------------------

class Recipient : public ::google::protobuf::Message {
 public:
  Recipient();
  virtual ~Recipient();

  Recipient(const Recipient& from);

  inline Recipient& operator=(const Recipient& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Recipient& default_instance();

  void Swap(Recipient* other);

  // implements Message ----------------------------------------------

  inline Recipient* New() const { return New(NULL); }

  Recipient* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Recipient& from);
  void MergeFrom(const Recipient& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Recipient* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // optional .yreflection.model.Email email = 2;
  bool has_email() const;
  void clear_email();
  static const int kEmailFieldNumber = 2;
  const ::yreflection::model::Email& email() const;
  ::yreflection::model::Email* mutable_email();
  ::yreflection::model::Email* release_email();
  void set_allocated_email(::yreflection::model::Email* email);

  // @@protoc_insertion_point(class_scope:yreflection.model.Recipient)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_email();
  inline void clear_has_email();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  ::yreflection::model::Email* email_;
  friend void  protobuf_AddDesc_model_2eproto();
  friend void protobuf_AssignDesc_model_2eproto();
  friend void protobuf_ShutdownFile_model_2eproto();

  void InitAsDefaultInstance();
  static Recipient* default_instance_;
};
// -------------------------------------------------------------------

class Message : public ::google::protobuf::Message {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  void Swap(Message* other);

  // implements Message ----------------------------------------------

  inline Message* New() const { return New(NULL); }

  Message* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // optional string subject = 2;
  bool has_subject() const;
  void clear_subject();
  static const int kSubjectFieldNumber = 2;
  const ::std::string& subject() const;
  void set_subject(const ::std::string& value);
  void set_subject(const char* value);
  void set_subject(const char* value, size_t size);
  ::std::string* mutable_subject();
  ::std::string* release_subject();
  void set_allocated_subject(::std::string* subject);

  // optional string body = 3;
  bool has_body() const;
  void clear_body();
  static const int kBodyFieldNumber = 3;
  const ::std::string& body() const;
  void set_body(const ::std::string& value);
  void set_body(const char* value);
  void set_body(const char* value, size_t size);
  ::std::string* mutable_body();
  ::std::string* release_body();
  void set_allocated_body(::std::string* body);

  // repeated .yreflection.model.Recipient recipients = 4;
  int recipients_size() const;
  void clear_recipients();
  static const int kRecipientsFieldNumber = 4;
  const ::yreflection::model::Recipient& recipients(int index) const;
  ::yreflection::model::Recipient* mutable_recipients(int index);
  ::yreflection::model::Recipient* add_recipients();
  ::google::protobuf::RepeatedPtrField< ::yreflection::model::Recipient >*
      mutable_recipients();
  const ::google::protobuf::RepeatedPtrField< ::yreflection::model::Recipient >&
      recipients() const;

  // @@protoc_insertion_point(class_scope:yreflection.model.Message)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_subject();
  inline void clear_has_subject();
  inline void set_has_body();
  inline void clear_has_body();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr subject_;
  ::google::protobuf::internal::ArenaStringPtr body_;
  ::google::protobuf::RepeatedPtrField< ::yreflection::model::Recipient > recipients_;
  friend void  protobuf_AddDesc_model_2eproto();
  friend void protobuf_AssignDesc_model_2eproto();
  friend void protobuf_ShutdownFile_model_2eproto();

  void InitAsDefaultInstance();
  static Message* default_instance_;
};
// -------------------------------------------------------------------

class Messages : public ::google::protobuf::Message {
 public:
  Messages();
  virtual ~Messages();

  Messages(const Messages& from);

  inline Messages& operator=(const Messages& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Messages& default_instance();

  void Swap(Messages* other);

  // implements Message ----------------------------------------------

  inline Messages* New() const { return New(NULL); }

  Messages* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Messages& from);
  void MergeFrom(const Messages& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Messages* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .yreflection.model.Message message = 1;
  int message_size() const;
  void clear_message();
  static const int kMessageFieldNumber = 1;
  const ::yreflection::model::Message& message(int index) const;
  ::yreflection::model::Message* mutable_message(int index);
  ::yreflection::model::Message* add_message();
  ::google::protobuf::RepeatedPtrField< ::yreflection::model::Message >*
      mutable_message();
  const ::google::protobuf::RepeatedPtrField< ::yreflection::model::Message >&
      message() const;

  // @@protoc_insertion_point(class_scope:yreflection.model.Messages)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::yreflection::model::Message > message_;
  friend void  protobuf_AddDesc_model_2eproto();
  friend void protobuf_AssignDesc_model_2eproto();
  friend void protobuf_ShutdownFile_model_2eproto();

  void InitAsDefaultInstance();
  static Messages* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Email

// optional string name = 1;
inline bool Email::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Email::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Email::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Email::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& Email::name() const {
  // @@protoc_insertion_point(field_get:yreflection.model.Email.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Email::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:yreflection.model.Email.name)
}
inline void Email::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yreflection.model.Email.name)
}
inline void Email::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yreflection.model.Email.name)
}
inline ::std::string* Email::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:yreflection.model.Email.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Email::release_name() {
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Email::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:yreflection.model.Email.name)
}

// optional string address = 2;
inline bool Email::has_address() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Email::set_has_address() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Email::clear_has_address() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Email::clear_address() {
  address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_address();
}
inline const ::std::string& Email::address() const {
  // @@protoc_insertion_point(field_get:yreflection.model.Email.address)
  return address_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Email::set_address(const ::std::string& value) {
  set_has_address();
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:yreflection.model.Email.address)
}
inline void Email::set_address(const char* value) {
  set_has_address();
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yreflection.model.Email.address)
}
inline void Email::set_address(const char* value, size_t size) {
  set_has_address();
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yreflection.model.Email.address)
}
inline ::std::string* Email::mutable_address() {
  set_has_address();
  // @@protoc_insertion_point(field_mutable:yreflection.model.Email.address)
  return address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Email::release_address() {
  clear_has_address();
  return address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Email::set_allocated_address(::std::string* address) {
  if (address != NULL) {
    set_has_address();
  } else {
    clear_has_address();
  }
  address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), address);
  // @@protoc_insertion_point(field_set_allocated:yreflection.model.Email.address)
}

// -------------------------------------------------------------------

// Recipient

// optional string type = 1;
inline bool Recipient::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Recipient::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Recipient::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Recipient::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_type();
}
inline const ::std::string& Recipient::type() const {
  // @@protoc_insertion_point(field_get:yreflection.model.Recipient.type)
  return type_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Recipient::set_type(const ::std::string& value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:yreflection.model.Recipient.type)
}
inline void Recipient::set_type(const char* value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yreflection.model.Recipient.type)
}
inline void Recipient::set_type(const char* value, size_t size) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yreflection.model.Recipient.type)
}
inline ::std::string* Recipient::mutable_type() {
  set_has_type();
  // @@protoc_insertion_point(field_mutable:yreflection.model.Recipient.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Recipient::release_type() {
  clear_has_type();
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Recipient::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    set_has_type();
  } else {
    clear_has_type();
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:yreflection.model.Recipient.type)
}

// optional .yreflection.model.Email email = 2;
inline bool Recipient::has_email() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Recipient::set_has_email() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Recipient::clear_has_email() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Recipient::clear_email() {
  if (email_ != NULL) email_->::yreflection::model::Email::Clear();
  clear_has_email();
}
inline const ::yreflection::model::Email& Recipient::email() const {
  // @@protoc_insertion_point(field_get:yreflection.model.Recipient.email)
  return email_ != NULL ? *email_ : *default_instance_->email_;
}
inline ::yreflection::model::Email* Recipient::mutable_email() {
  set_has_email();
  if (email_ == NULL) {
    email_ = new ::yreflection::model::Email;
  }
  // @@protoc_insertion_point(field_mutable:yreflection.model.Recipient.email)
  return email_;
}
inline ::yreflection::model::Email* Recipient::release_email() {
  clear_has_email();
  ::yreflection::model::Email* temp = email_;
  email_ = NULL;
  return temp;
}
inline void Recipient::set_allocated_email(::yreflection::model::Email* email) {
  delete email_;
  email_ = email;
  if (email) {
    set_has_email();
  } else {
    clear_has_email();
  }
  // @@protoc_insertion_point(field_set_allocated:yreflection.model.Recipient.email)
}

// -------------------------------------------------------------------

// Message

// optional string id = 1;
inline bool Message::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Message::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Message::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Message::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_id();
}
inline const ::std::string& Message::id() const {
  // @@protoc_insertion_point(field_get:yreflection.model.Message.id)
  return id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_id(const ::std::string& value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:yreflection.model.Message.id)
}
inline void Message::set_id(const char* value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yreflection.model.Message.id)
}
inline void Message::set_id(const char* value, size_t size) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yreflection.model.Message.id)
}
inline ::std::string* Message::mutable_id() {
  set_has_id();
  // @@protoc_insertion_point(field_mutable:yreflection.model.Message.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Message::release_id() {
  clear_has_id();
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    set_has_id();
  } else {
    clear_has_id();
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:yreflection.model.Message.id)
}

// optional string subject = 2;
inline bool Message::has_subject() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Message::set_has_subject() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Message::clear_has_subject() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Message::clear_subject() {
  subject_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_subject();
}
inline const ::std::string& Message::subject() const {
  // @@protoc_insertion_point(field_get:yreflection.model.Message.subject)
  return subject_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_subject(const ::std::string& value) {
  set_has_subject();
  subject_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:yreflection.model.Message.subject)
}
inline void Message::set_subject(const char* value) {
  set_has_subject();
  subject_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yreflection.model.Message.subject)
}
inline void Message::set_subject(const char* value, size_t size) {
  set_has_subject();
  subject_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yreflection.model.Message.subject)
}
inline ::std::string* Message::mutable_subject() {
  set_has_subject();
  // @@protoc_insertion_point(field_mutable:yreflection.model.Message.subject)
  return subject_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Message::release_subject() {
  clear_has_subject();
  return subject_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_subject(::std::string* subject) {
  if (subject != NULL) {
    set_has_subject();
  } else {
    clear_has_subject();
  }
  subject_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), subject);
  // @@protoc_insertion_point(field_set_allocated:yreflection.model.Message.subject)
}

// optional string body = 3;
inline bool Message::has_body() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Message::set_has_body() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Message::clear_has_body() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Message::clear_body() {
  body_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_body();
}
inline const ::std::string& Message::body() const {
  // @@protoc_insertion_point(field_get:yreflection.model.Message.body)
  return body_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_body(const ::std::string& value) {
  set_has_body();
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:yreflection.model.Message.body)
}
inline void Message::set_body(const char* value) {
  set_has_body();
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yreflection.model.Message.body)
}
inline void Message::set_body(const char* value, size_t size) {
  set_has_body();
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yreflection.model.Message.body)
}
inline ::std::string* Message::mutable_body() {
  set_has_body();
  // @@protoc_insertion_point(field_mutable:yreflection.model.Message.body)
  return body_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Message::release_body() {
  clear_has_body();
  return body_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_body(::std::string* body) {
  if (body != NULL) {
    set_has_body();
  } else {
    clear_has_body();
  }
  body_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), body);
  // @@protoc_insertion_point(field_set_allocated:yreflection.model.Message.body)
}

// repeated .yreflection.model.Recipient recipients = 4;
inline int Message::recipients_size() const {
  return recipients_.size();
}
inline void Message::clear_recipients() {
  recipients_.Clear();
}
inline const ::yreflection::model::Recipient& Message::recipients(int index) const {
  // @@protoc_insertion_point(field_get:yreflection.model.Message.recipients)
  return recipients_.Get(index);
}
inline ::yreflection::model::Recipient* Message::mutable_recipients(int index) {
  // @@protoc_insertion_point(field_mutable:yreflection.model.Message.recipients)
  return recipients_.Mutable(index);
}
inline ::yreflection::model::Recipient* Message::add_recipients() {
  // @@protoc_insertion_point(field_add:yreflection.model.Message.recipients)
  return recipients_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::yreflection::model::Recipient >*
Message::mutable_recipients() {
  // @@protoc_insertion_point(field_mutable_list:yreflection.model.Message.recipients)
  return &recipients_;
}
inline const ::google::protobuf::RepeatedPtrField< ::yreflection::model::Recipient >&
Message::recipients() const {
  // @@protoc_insertion_point(field_list:yreflection.model.Message.recipients)
  return recipients_;
}

// -------------------------------------------------------------------

// Messages

// repeated .yreflection.model.Message message = 1;
inline int Messages::message_size() const {
  return message_.size();
}
inline void Messages::clear_message() {
  message_.Clear();
}
inline const ::yreflection::model::Message& Messages::message(int index) const {
  // @@protoc_insertion_point(field_get:yreflection.model.Messages.message)
  return message_.Get(index);
}
inline ::yreflection::model::Message* Messages::mutable_message(int index) {
  // @@protoc_insertion_point(field_mutable:yreflection.model.Messages.message)
  return message_.Mutable(index);
}
inline ::yreflection::model::Message* Messages::add_message() {
  // @@protoc_insertion_point(field_add:yreflection.model.Messages.message)
  return message_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::yreflection::model::Message >*
Messages::mutable_message() {
  // @@protoc_insertion_point(field_mutable_list:yreflection.model.Messages.message)
  return &message_;
}
inline const ::google::protobuf::RepeatedPtrField< ::yreflection::model::Message >&
Messages::message() const {
  // @@protoc_insertion_point(field_list:yreflection.model.Messages.message)
  return message_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace model
}  // namespace yreflection

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_model_2eproto__INCLUDED
